[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
heck = "0.5.0"
ungrammar = "1.16.1"
quote = "1.0.40"
xshell = "0"
serde = { workspace = true }
serde_json = { workspace = true }
serde-xml-rs = "0.8.1"
proc-macro2 = "1"